name: Feature tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Restore cached environment
      uses: actions/cache@v3
      with:
        path: test-env/
        key: ${{ runner.os }}-env-${{ hashFiles('pyproject.toml') }}

    - name: Set up environment
      shell: bash
      run: |
        if [ ! -d "test-env" ]; then
          python3 -m venv test-env
        fi
        source test-env/bin/activate
        pip install --upgrade pip

    - name: Install dependencies
      shell: bash
      run: |
        source test-env/bin/activate
        pip install . pytest

    - name: Run tests
      shell: bash
      run: |
        source test-env/bin/activate
        pytest -v --color=yes src/pacu/features/
