name: Feature tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment
      shell: bash
      run: |
        python3 -m venv test-env
        source test-env/bin/activate
        pip install --upgrade pip

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      shell: bash
      run: |
        source test-env/bin/activate
        pip install . pytest

    - name: Run tests
      shell: bash
      run: |
        source test-env/bin/activate
        pytest -v --color=yes src/pacu/features/
